config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index'
  resources :flavors do
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
      get 'image'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flavor.rb
# frozen_string_literal: true

class Flavor < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader

  def self.search(search)
    return Flavor.all unless search

    Flavor.where(['name LIKE ?', "%#{search}%"]).where(id: 2..25).limit(10)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :flavors
  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  def after_inactive_sign_up_for(_resource)
    flavors_path
  end

  def after_sign_in_path_for(_resource)
    flavors_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end
end

app/controllers/flavors_controller.rb
# frozen_string_literal: true

class FlavorsController < ApplicationController
  before_action :authenticate_user!
  def index
    @flavors = Flavor.where(id: 2..25).order(id: 'ASC').page(params[:page]).per(10)
    @status_image = ['', 'urn_red.png', 'urn_yellow.png', 'urn_blue.png']
  end

  def new
    @flavor = Flavor.new
  end

  def create
    @flavor = Flavor.new(flavor_params)
    @flavor.save
    redirect_to flavors_path
  end

  def edit
    @flavor = Flavor.find(params[:id])
    render 'edit.js.erb'
  end

  def update
    @flavor = Flavor.find(params[:id])
    @flavor.update(flavor_params)
    if @flavor.status == 1
      @flavors_1 = Flavor.where(status: 1)
      @users = User.all
      user_ids = @users.map(&:id)
      flavor_ids = @flavors_1.map(&:id)
      FlavorMailer.send_status_1(user_ids, flavor_ids).deliver_later
    end
    @flavors = Flavor.all.order(id: 'ASC').page(params[:page]).per(10)
    redirect_to flavors_path
  end

  def search
    @flavors = Flavor.search(params[:search])
    @status_image = ['', 'urn_red.png', 'urn_yellow.png', 'urn_blue.png']
  end

  private

  def flavor_params
    params.require(:flavor).permit(:name, :purchase_price, :image, :image_cache, :status).merge(user_id: current_user.id)
  end
end

app/controllers/top_controller.rb
# frozen_string_literal: true

class TopController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @flavors = current_user.flavors.order(id: 'ASC').page(params[:page]).per(5)
  end

  def image
    @flavors = current_user.flavors
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/flavors_helper.rb
# frozen_string_literal: true

module FlavorsHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

module TopHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/flavors/edit.js.erb
$("#flavor-modal").html("<%= escape_javascript(render 'layouts/form') %>")
$("#flavor-modal").modal("toggle")

app/views/flavors/index.html.erb
<div class="wrapper">
    <div class="flavors-pagination-wrapper">
        <div class="flavors-wrapper">
            <% @flavors.each do |flavor| %>
                <div class="flavor">
                    <%= link_to image_tag(@status_image[flavor.status]), edit_flavor_path(flavor), remote: true, class: "StatusImage" %>
                    <p><%= flavor.name %></p>
                </div>
            <% end %>
            <div class="empty">
                <%= paginate(@flavors) %>
            </div>
        </div>
    </div>
</div>
<div id="flavor-modal"></div>

app/views/flavors/new.html.erb
<div class="wrapper">
    <div class="resistration-wrapper">
        <h2>購入</h2>
        <div class="form-wrapper">
            <%= form_for(@flavor) do |f| %>
            <table class="form-table">
                <tbody>
                    <tr>
                        <th>調味料</th>
                        <td><%= f.text_field :name %></td>
                    </tr>
                    <tr>
                        <th>価格</th>
                        <td><%= f.text_field :purchase_price %></td>
                    </tr>
                    <tr>
                        <th>レシート</th>
                        <td><%= f.file_field :image %></td>
                    </tr>

                </tbody>
            </table>
                <div class="submit-wrapper">
                    <div class="action-wrapper">
                        <%= f.submit "Send", class: "action" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/flavors/search.html.erb
<div class="wrapper">
    <div class="flavors-pagination-wrapper">
        <div class="flavors-wrapper">
            <% @flavors.each do |flavor| %>
                <div class="flavor">
                    <%= link_to image_tag(@status_image[flavor.status]), edit_flavor_path(flavor), remote: true, class: "StatusImage" %>
                    <p><%= flavor.name %></p>
                </div>
            <% end %>
        </div>
    </div>
</div>
<div id="flavor-modal"></div>

app/views/layouts/_footer.html.erb
<header>
    <nav class="header-flex">
        <%= link_to "Chells Kitchen", flavors_path,  class: "header-logo"%>
        <ul class="header-items">
            <% if user_signed_in? %>
            <li>
                <%= link_to "購入", new_flavor_path %>
            </li>
            <li>
                <%= link_to "マイページ", user_path(current_user) %>
            </li>
            <li>
                <%= link_to "ログアウト", destroy_user_session_path %>
            </li>
            <li>
                <%= form_tag(search_flavors_path, :method => 'get') do %>
                    <%= text_field_tag :search,"", {class: "search-field", size: "15"}%>
                    <%= submit_tag '検索', :name => nil, :class => "search-button"%>
                <% end %>
            </li>
            <% else %>
            <li>
                <%= link_to "サインアップ", new_user_registration_path %>
            </li>
            <li>
                <%= link_to "ログイン", new_user_session_path %>
            </li>
            <% end %>
        </ul>
    </nav>
</header>

app/views/layouts/_form.html.erb
<div class="modal__bg js-modal-close">
   <div class="modal__content">
   <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
   </button>
      <%= form_with(model: @flavor, local: true) do |form| %>
      <div class="modal-header">
        <h5 class="modal-title">ステータスを変更</h5>
      </div>
      <div class="modal-body">
            <div class="form-group field">
               <div class="modal_explanation">
                  <div class="urn">
                     <%= image_tag ('urn_red.png')%>
                     <p>1</p>
                  </div>
                  <div class="urn">
                     <%= image_tag ('urn_yellow.png')%>
                     <p>2</p>
                  </div>
                  <div class="urn">
                     <%= image_tag ('urn_blue.png')%>
                     <p>3</p>
                  </div>
               </div>
               <%= form.select :status, [1,2,3] %>
            </div>
      </div>
         <div class="modal-footer actions">
            <%= form.submit "アップデート", class: "update-button" %>
            <%= link_to "購入", new_flavor_path, class:"purchase-button" %>
         </div>
         <% end %>
   </div>
</div>

app/views/layouts/_header.html.erb
<header>
    <nav class="header-flex">
        <%= link_to "Chells Kitchen", flavors_path,  class: "header-logo"%>
        <ul class="header-items">
            <% if user_signed_in? %>
            <li>
                <%= link_to "購入", new_flavor_path %>
            </li>
            <li>
                <%= link_to "マイページ", user_path(current_user) %>
            </li>
            <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
            <li>
                <%= form_tag(search_flavors_path, :method => 'get') do %>
                    <%= text_field_tag :search,"", {class: "search-field", size: "15"}%>
                    <%= submit_tag '検索', :name => nil, :class => "search-button"%>
                <% end %>
            </li>
            <% else %>
            <li>
                <%= link_to "サインアップ", new_user_registration_path %>
            </li>
            <li>
                <%= link_to "ログイン", new_user_session_path %>
            </li>
            <% end %>
        </ul>
        <div class="dropdown">
            <%= image_tag "dropdown_menu.png", :id => "sized" %>
        </div>
    </nav>
</header>
<div id="myModal" class="modal">
<div class="modal-content animated zoomIn">
      <div class="modal-header">
         <span class="close">×</span>
     </div>

    <div class="modal-body nav">
       <ul class="modal-nav">
            <% if user_signed_in? %>
            <li>
                <%= link_to "購入", new_flavor_path %>
            </li>
            <li>
                <%= link_to "マイページ", user_path(current_user) %>
            </li>
            <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
            <li>
                <%= form_tag(search_flavors_path, :method => 'get') do %>
                    <%= text_field_tag :search,"", {class: "search-field", size: "15"}%>
                    <%= submit_tag '検索', :name => nil, :class => "search-button"%>
                <% end %>
            </li>
            <% else %>
            <li>
                <%= link_to "サインアップ", new_user_registration_path %>
            </li>
            <li>
                <%= link_to "ログイン", new_user_session_path %>
            </li>
            <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "header.js" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChellsKitchen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif|M+PLUS+1p:300,400,500,700&display=swap&subset=japanese" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/top/index.html.erb
<div>
    <div id="main-image">
        <h2><span style="color: #cc2931">Chells Kitchen</span>は<br>キッチンの調味料の<br>調整をするサービスです。</h2>
    </div>
    <div class="wrapper">
    <section>
        <div class="section1 section">
            <div class="number">
                <%= image_tag '01.png', class: "number-image" %>
                <div class="text">
                    <h2 class="text-title">どこでも調味料の状態が<br>わかります</h2>
                    <p class="text-p">調味料が切れそうならChells-Kitchenを利用しよう。<br>
                    Web上で調味料を更新すれば、寮生に通知が入ります。<br>
                    外出中の寮生に買ってきてもらいましょう。
                    </p>
                </div>
            </div>
            <div class="image">
                <%= image_tag "iphone.png" %>
            </div>
        </div>
        <div class="section2 section">
            <div class="number">
                <%= image_tag '02.png', class: "number-image" %>
                <div class="text02">
                    <h2 class="text-title">レシートいらず、写真で送ろう。</h2>
                    <p class="text-p">返金にレシートが必要でした。<br>
                    Chells-Kitchenではレシートの必要はありません。<br>
                    調味料を買ったらレシートの写真を撮って<br>
                    webにあげましょう。<br>
                    そうすればお金が返ってきます。
                    </p>
                </div>
            </div>
            <div class="image">
                <%= image_tag "send.png" %>
            </div>
        </div>
        <div class="section3 section">
            <div class="number">
                <%= image_tag '03.png', class: "number-image" %>
                <div class="text02">
                    <h2 class="text-title">キッチンでの<br>コミュニケーションアップ</h2>
                    <p class="text-p">調味料が不足している時、<br>
                    調味料を誰かが購入した時、寮生に通知が入ります。<br>
                    寮生が感謝を伝え合い、コミュニケーションが<br>
                    増えることを製作者は期待しています。<br>
                    みんな調味料買ってね。</p>
                </div>
            </div>
            <div class="image">
                <%= image_tag "suke.png" %>
            </div>
        </div>
    </section>
    <div class="try-use">
        <%= link_to new_user_registration_path do %>
            <%= image_tag "try-use.png" %>
        <% end %>
    </div>
    </div>
</div>

app/views/users/image.html.erb
<% @flavors.each do |flavor| %>
   <%= flavor.name %>
   <% if flavor.image? %>
      <%= image_tag flavor.image.url %>
   <% end %>
   <%= flavor.created_at.strftime('%Y/%m/%d') %>
<% end %>

app/views/users/show.html.erb
<div class="wrapper">
    <div class="resistration-wrapper">
        <h2>
            マイページ
        </h2>
        <div class="form-wrapper">
            <div class="mypage-flavors">
                <table class="form-table">
                    <tbody>
                    <% @flavors.each do |flavor| %>
                        <tr>
                            <th><%= flavor.name %></th>
                            <td><%= flavor.purchase_price %>円</td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
                <div class="total-reseat">
                    <p class="price-all">合計: <%= @flavors.all.sum(:purchase_price) %>円</p>
                    <%= link_to "レシート一覧", image_user_path(current_user), class: "images_link"%>
                </div>
                <div class="empty">
                    <%= paginate(@flavors) %>
                </div>
            </div>
        </div>
    </div>
</div>